### ISSUE TITLE
❓ Question: Filter by video type (shorts vs regular video)

### ISSUE THREAD

**Issue by Balastrong** [DenverCoder1/github-readme-youtube-cards#92]
### Description

I'm asking it as a question because I'm not even sure if it's possible from the APIs, but would be possible to filter the shorts?

I'd like to show on my profile only "regular" videos, not shorts, as they don't have a cover image and I don't like too much the final result on my profile.

**Comment by DenverCoder1** [comment]
From what I can tell, it doesn't appear that the XML feed or API have a way of distinguishing between "shorts" and regular videos.

Maybe a filter on the maximum video length could work, but it does complicate things a bit since the duration can only be retrieved through the API so it seemingly would require requesting more than `max_videos` videos from the YouTube API and filtering down afterwards.

**Comment by airscholar** [comment]
@DenverCoder1 I saw this [stackoverflow](https://stackoverflow.com/questions/71192605/how-do-i-get-youtube-shorts-from-youtube-api-data-v3) thread and thought it might help.

**Comment by Balastrong** [comment]
I posted a couple of shorts on youtube last week after quite some time and I was wondering again about the state of this issue.

The solution is brilliant and works perfectly, thanks @airscholar and @DenverCoder1! 🚀
